# Définition d'un tableau de routes au format TOML (https://toml.io/)
# - url : chemin dans l'URL
# - controleur : chemin vers le fichier du controleur
# - template : chemin vers le fichier de template

[[routes]]
url = ""
controleur = "controleurs/accueil/accueil.py"
template = "templates/accueil/accueil.html"
[[routes]]
url = "partie-simple"
controleur = "controleurs/partie_simple/jouer.py"
template = "templates/partie_simple/jouer.html"
[[routes]]
url = "partie-simple/creer"
controleur = "controleurs/partie_simple/creer.py" # peut être utiliser deux fois le même
template = "templates/partie_simple/creer.html"
[[routes]]
url = "equipe"
controleur = "controleurs/equipe/lister.py"
template = "templates/equipe/lister.html"
[[routes]]
url = "equipe/creer"
controleur = "controleurs/equipe/creation.py"
template = "templates/equipe/creation.html"
[[routes]]
url = "[0-9]/"
controleur = "controleurs/equipe/creation.py"
template = "templates/equipe/creation.html"


