# Définition d'un tableau de routes au format TOML (https://toml.io/)
# - url : chemin dans l'URL
# - controleur : chemin vers le fichier du controleur
# - template : chemin vers le fichier de template

#
# DIVERS
#

[[routes]]
url = ""
controleur = "controleurs/accueil/accueil.py"
template = "templates/accueil/accueil.html"
[[routes]]
url = "parties"
controleur = "controleurs/liste_partie.py"
template = "templates/liste_partie.html"
#
# PARTIE
#
[[routes]]
url = "combat"
controleur = "controleurs/partie/combat/jouer.py"
template = "templates/partie/jouer.html"

[[routes]]
url = "combat/fin"
controleur = "controleurs/partie/combat/resultat.py"
template = "templates/partie/resultat.html"

[[routes]]
url = "partie"
controleur = "controleurs/partie/jouer.py"
template = "templates/partie/jouer.html"

[[routes]]
url = "partie/fin"
controleur = "controleurs/partie/resultat.py"
template = "templates/partie/resultat.html"

[[routes]]
url = "partie/creer"
controleur = "controleurs/partie/creer.py" # peut être utiliser deux fois le même
template = "templates/partie/creer.html"


[[routes]]
url = "partie/resultat"
controleur = "controleurs/partie/resultat.py" # peut être utiliser deux fois le même
template = "templates/partie/resultats.html"

#
# EQUIPE
#
[[routes]]
url = "equipes"
controleur = "controleurs/equipe/lister.py"
template = "templates/equipe/lister.html"
[[routes]]
url = "equipe/creer"
controleur = "controleurs/equipe/creation.py"
template = "templates/equipe/creation.html"
